#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Dec 14, 2022 11:10:56 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import member
#email="gmail"
#password="1234"
#peopleArray = []
#peopleArray.append(["gmail","1234"])
#global email
#email=""
#global password
#password=""
_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = member.Toplevel1(_top1)
    root.mainloop()
    

def onClickLogBtn(*args):
    print("click")

def onClickSignBtn(*args):
    print("click")


if __name__ == '__main__':
    member.start_up()

