#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Dec 16, 2022 01:33:22 AM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    image55 "../111.png" 
    record_png "../record.png" 
    analysis_png "../analysis.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m58" -relief ridge -background #faf4e0 \
        -highlightbackground #faf4e0 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+273+146
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 681
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "錢包管家系統"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Homepage" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but47" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "載具記帳" 
    vTcl:DefineAlias "$top.but47" "Button_scan" vTcl:WidgetProc "Homepage" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but49" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -command "RecordMenu" -compound center -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "消費紀錄與分析" 
    vTcl:DefineAlias "$top.but49" "Button_record" vTcl:WidgetProc "Homepage" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but50" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "需求分析" 
    vTcl:DefineAlias "$top.but50" "Button_demand" vTcl:WidgetProc "Homepage" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but51" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -command "UserWin" -compound center -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "會員頁面" 
    vTcl:DefineAlias "$top.but51" "Button_user" vTcl:WidgetProc "Homepage" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab52" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #faf4e0 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image55 -text "Label" 
    vTcl:DefineAlias "$top.lab52" "icon" vTcl:WidgetProc "Homepage" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab53" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #faf4e0 -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family 微軟正黑體 -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "錢包管家系統" 
    vTcl:DefineAlias "$top.lab53" "title" vTcl:WidgetProc "Homepage" 1
### SPOT dump_widget_opt A
    ttk::style configure Menu -background $vTcl(actual_gui_bg)
    ttk::style configure Menu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Menu -font "$vTcl(actual_gui_font_dft_desc)"
    menu "$top.m58" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but47 \
        -in $top -x 0 -relx 0.233 -y 0 -rely 0.489 -width 108 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.567 -y 0 -rely 0.489 -width 108 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.233 -y 0 -rely 0.667 -width 108 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.567 -y 0 -rely 0.667 -width 108 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.367 -y 0 -rely 0.156 -width 0 -relwidth 0.195 \
        -height 0 -relheight 0.224 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.378 -width 0 -relwidth 0.212 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m54" -background #faf4e0 -highlightbackground #faf4e0 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+378+149
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "消費紀錄與分析"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure Menu -background $vTcl(actual_gui_bg)
    ttk::style configure Menu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Menu -font "$vTcl(actual_gui_font_dft_desc)"
    menu "$top.m54" \
        -activebackground #faf4e0 -activeforeground #000000 \
        -background #faf4e0 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but55" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -command "checkRecord" -compound left -disabledforeground #a3a3a3 \
        -font "-family 微軟正黑體 -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "消費記錄明細" 
    vTcl:DefineAlias "$top.but55" "Button_record" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but56" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -command "checkAnalysis" -compound left -disabledforeground #a3a3a3 \
        -font "-family 微軟正黑體 -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "消費習慣分析" 
    vTcl:DefineAlias "$top.but56" "Button_analysis" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab57" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #faf4e0 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image record_png -text "Label" 
    vTcl:DefineAlias "$top.lab57" "pic1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab59" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #faf4e0 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image analysis_png -text "Label" 
    vTcl:DefineAlias "$top.lab59" "pic2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but47" \
        -activebackground #6cc2f7 -activeforeground black -background #b5e0fb \
        -command "toHomepage" -compound left -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text "返回" 
    vTcl:DefineAlias "$top.but47" "Button_return " vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but55 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.622 -width 128 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.6 -y 0 -rely 0.622 -width 128 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.289 -width 0 -relwidth 0.212 \
        -height 0 -relheight 0.269 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.567 -y 0 -rely 0.289 -width 0 -relwidth 0.245 \
        -height 0 -relheight 0.269 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 68 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background #faf4e0 
    wm focusmodel $top passive
    wm geometry $top 599x450+174+162
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm iconify $top
    set toptitle "消費紀錄明細"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "DetailWin" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure Menu -background $vTcl(actual_gui_bg)
    ttk::style configure Menu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Menu -font "$vTcl(actual_gui_font_dft_desc)"
    menu "$top.m48" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    ttk::style configure Popupmenu -background $vTcl(actual_gui_bg)
    ttk::style configure Popupmenu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Popupmenu -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::core::popup::createCmd "$top.pop51" \
        -activebackground $vTcl(analog_color_m) -activeborderwidth 1 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -borderwidth 1 -disabledforeground #a3a3a3 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl($top.pop51,-proc)
    set vTcl($top.pop51,-proc) popup1
    namespace eval ::widgets::$top.pop51 {}
    set ::widgets::$top.pop51::ClassOption(-proc) popup1
    set ::widgets::$top.pop51::options(-proc) popup1
    set ::widgets::$top.pop51::save(-proc) 1
    vTcl:DefineAlias "$top.pop51" "Popupmenu1" vTcl:WidgetProc "" 1
### SPOT dump_widget_opt A
    ttk::style configure Popupmenu -background $vTcl(actual_gui_bg)
    ttk::style configure Popupmenu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Popupmenu -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::core::popup::createCmd "$top.pop52" \
        -activebackground $vTcl(analog_color_m) -activeborderwidth 1 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -borderwidth 1 -disabledforeground #a3a3a3 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl($top.pop52,-proc)
    set vTcl($top.pop52,-proc) popup2
    namespace eval ::widgets::$top.pop52 {}
    set ::widgets::$top.pop52::ClassOption(-proc) popup2
    set ::widgets::$top.pop52::options(-proc) popup2
    set ::widgets::$top.pop52::save(-proc) 1
    vTcl:DefineAlias "$top.pop52" "Popupmenu2" vTcl:WidgetProc "" 1
### SPOT dump_widget_opt A
    ttk::style configure Popupmenu -background $vTcl(actual_gui_bg)
    ttk::style configure Popupmenu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Popupmenu -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::core::popup::createCmd "$top.pop54" \
        -activebackground $vTcl(analog_color_m) -activeborderwidth 1 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -borderwidth 1 -disabledforeground #a3a3a3 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl($top.pop54,-proc)
    set vTcl($top.pop54,-proc) popup3
    namespace eval ::widgets::$top.pop54 {}
    set ::widgets::$top.pop54::ClassOption(-proc) popup3
    set ::widgets::$top.pop54::options(-proc) popup3
    set ::widgets::$top.pop54::save(-proc) 1
    vTcl:DefineAlias "$top.pop54" "Popupmenu3" vTcl:WidgetProc "" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab56" \
        -activeforeground SystemButtonText -background #faf4e0 \
        -compound center -disabledforeground #a3a3a3 \
        -font "-family 微軟正黑體 -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "消費紀錄明細" 
    vTcl:DefineAlias "$top.lab56" "record_title" vTcl:WidgetProc "DetailWin" 1
### SPOT dump_widget_opt A
    ttk::style configure Listbox -background $vTcl(actual_gui_bg)
    ttk::style configure Listbox -foreground $vTcl(actual_gui_fg)
    ttk::style configure Listbox -font "$vTcl(actual_gui_font_dft_desc)"
    listbox "$top.lis59" \
        -background #fdfbf4 -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 310 -width 444 \
        -listvariable "record" 
    $top.lis59 configure -font "TkFixedFont"
    $top.lis59 insert end text
    vTcl:DefineAlias "$top.lis59" "showRecord" vTcl:WidgetProc "DetailWin" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab56 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.089 -width 0 -relwidth 0.778 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lis59 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.2 -width 0 -relwidth 0.74 \
        -height 0 -relheight 0.689 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}

